[package]
name = "viac_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_matches = { workspace = true }
escape_string = "0.1.2"
via_macros = { path = "../via_macros" }
via_proc_macros = { path = "../via_proc_macros" }
viac_diags = { path = "../viac_diags" }
viac_ast = { path = "../viac_ast" }
viac_lexer = { path = "../viac_lexer" }
viac_source = { path = "../viac_source" }
