[package]
name = "viac"
version = "0.1.0"
edition = "2024"
publish = true

[dependencies]
via_macros = { path = "../via_macros" }
via_proc_macros = { path = "../via_proc_macros" }
assert_matches.workspace = true
bitflags.workspace = true
itertools.workspace = true
anyhow.workspace = true
phf.workspace = true
derive_more = { workspace = true, features = ["from"] }
escape_string = "0.1.2"
bimap = "0.6.3"
unicode-ident = "1.0.22"
strum = { version = "0.27.2", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.18"
