/* ================================================ **
**           The via Programming Language           **
** ------------------------------------------------ **
**        Copyright (C) XnLogicaL 2024-2026         **
**           Licensed under GNU GPL v3.0            **
** ------------------------------------------------ **
**         https://github.com/via-lang/via          **
** ================================================ */

use std::marker::PhantomData;

#[derive(Debug, PartialEq, Eq, Hash)]
pub struct NodeId<T> {
    index: u32,
    _marker: PhantomData<*const T>,
}

impl<T> Clone for NodeId<T> {
    fn clone(&self) -> Self {
        Self {
            index: self.index,
            _marker: PhantomData,
        }
    }
}

impl<T> Copy for NodeId<T> {}

impl<T> NodeId<T> {
    pub fn new(index: u32) -> Self {
        Self {
            index,
            _marker: PhantomData,
        }
    }

    pub fn index(&self) -> u32 {
        self.index
    }
}

pub trait NodeStore<T> {
    fn get(&self, id: NodeId<T>) -> &T;
}

pub trait Visitor {
    // one method per node type — user overrides what they care about
    // default impls call the walk_* functions generated by #[derive(Visitor)]
}
